---
- name: Make sure the main confs are present
  become: yes
  template:
    src: "nginx.conf.j2"
    dest: "{{ nginx.server_root }}/nginx.conf"
  notify: reload nginx

- name: Make sure the custom confs are present
  become: yes
  template:
    src: "http.conf.j2"
    dest: "{{ nginx.server_root }}/conf.d/http.conf"
  notify: reload nginx
  when: nginx.http is defined

- name: Make sure the servers are present
  become: yes
  template:
    src: "server.conf.j2"
    dest: "{{ nginx.server_root }}/conf.d/{{ item.server_name }}.conf"
  with_items: "{{ nginx.servers }}"
  notify: reload nginx
  when: item.server_name is defined
